name: push

on:
  - push

jobs:
  push:
    name: push

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install dotnet 2.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x
     
      - name: install dotnet 2.2.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.x

      - name: install dotnet 3.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.x

      - name: install dotnet 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: install dotnet 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: install packages
        run: dotnet restore 

      - name: build
        run: dotnet build

      - name: test 
        run: dotnet test -c Release