name: publish
on:
  release:
    types: [published]
    branches:
      - master # Default release branch
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: install dotnet 2.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x
     
      - name: install dotnet 2.2.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.x

      - name: install dotnet 3.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.x

      - name: install dotnet 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: install dotnet 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: build
        run: dotnet build

      - name: test
        run: dotnet test -c Release
        
      - name: publish
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Byndyusoft.AspNetCore.Cors.csproj
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true